// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-records.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-records.ts
var list_records_default = defineTool({
  name: "list_records",
  title: "List scheduling records",
  description: "List rows from a scheduling table: teachers, subjects, rooms, batches, or timeslots.",
  inputSchema: {
    table: z.enum(["teachers", "subjects", "rooms", "batches", "timeslots"]).describe("Which scheduling table to read."),
    limit: z.number().int().min(1).max(200).default(100).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from(table).select("*").limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { table, rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-timetable.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_timetable_default = defineTool2({
  name: "get_timetable",
  title: "Get timetable",
  description: "Read the generated weekly timetable with subject, teacher, room, batch and time slot details. Optionally filter by batch name, teacher name, or day.",
  inputSchema: {
    batch: z2.string().trim().optional().describe("Filter to a batch name (case-insensitive)."),
    teacher: z2.string().trim().optional().describe("Filter to a teacher name (case-insensitive)."),
    day: z2.string().trim().optional().describe("Filter to a day, e.g. Monday.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ batch, teacher, day }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("timetable").select(
      "id, subjects(name, code, type), teachers(name, email), rooms(number, type), batches(name, semester), timeslots(day, start_time, end_time)"
    );
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((row) => ({
      subject: row.subjects?.name ?? null,
      subject_code: row.subjects?.code ?? null,
      teacher: row.teachers?.name ?? null,
      room: row.rooms?.number ?? null,
      batch: row.batches?.name ?? null,
      semester: row.batches?.semester ?? null,
      day: row.timeslots?.day ?? null,
      start_time: row.timeslots?.start_time ?? null,
      end_time: row.timeslots?.end_time ?? null
    })).filter(
      (r) => (!batch || (r.batch ?? "").toLowerCase().includes(batch.toLowerCase())) && (!teacher || (r.teacher ?? "").toLowerCase().includes(teacher.toLowerCase())) && (!day || (r.day ?? "").toLowerCase() === day.toLowerCase())
    ).sort((a, b) => `${a.day}${a.start_time}`.localeCompare(`${b.day}${b.start_time}`));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { entries: rows }
    };
  }
});

// src/lib/mcp/tools/add-teacher.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var add_teacher_default = defineTool3({
  name: "add_teacher",
  title: "Add teacher",
  description: "Create a new teacher record with a name and email.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Teacher full name."),
    email: z3.string().trim().min(3).describe("Teacher email address.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("teachers").insert({ name, email }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { teacher: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sicdmiiylyfcaidowvyt";
var mcp_default = defineMcp({
  name: "academa-schedule-gen",
  title: "academa-schedule-gen",
  version: "0.1.0",
  instructions: "Tools for the Academa Scheduler timetable app. Use `list_records` to read teachers, subjects, rooms, batches, or time slots; `get_timetable` to read the generated weekly schedule (filterable by batch, teacher, or day); and `add_teacher` to create a teacher. Timetable generation itself happens in the app UI.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_records_default, get_timetable_default, add_teacher_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
